# Generated by Django 4.0.3 on 2022-03-16 10:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField()),
                ('is_paused', models.BooleanField()),
                ('is_stopped', models.BooleanField()),
                ('started_at', models.DateTimeField()),
                ('stopped_at', models.DateTimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelog', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
