# Generated by Django 4.0.3 on 2022-03-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
