# Generated by Django 4.0.3 on 2022-03-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_timelog_is_paused_alter_timelog_is_running_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='stopped_at',
            field=models.DateTimeField(null=True),
        ),
    ]
