# Generated by Django 4.0.3 on 2022-03-16 13:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0011_alter_timelog_started_at_alter_timelog_stopped_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='is_paused',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='is_running',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='is_stopped',
        ),
        migrations.AlterField(
            model_name='timelog',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_stopped', models.BooleanField(default=False)),
                ('is_running', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
