# Generated by Django 4.0.3 on 2022-03-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_timelog_is_paused_remove_timelog_is_running_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='stopped_at',
        ),
        migrations.AlterField(
            model_name='timelog',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='started_at',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
