# Generated by Django 4.0.3 on 2022-03-17 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_timelog_stopped_at_alter_timelog_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelog', to='tasks.task'),
        ),
    ]
